# Generated by Django 5.0.1 on 2024-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_location_track_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='donateStatus',
            field=models.BooleanField(blank=True, choices=[(True, 'Available'), (False, 'Already Donated')], default=True, null=True),
        ),
    ]
